# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Integration Tests

on:
  push:
    branches: [ main ]

env:
  NODE_VERSION: '10.x'
  PYTHON_VERSION: 3.10.0

jobs:
  integration-tests-main:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        pip install -e .

    - name: Install Ganache and Truffle through NPM
      run: |
        npm install -g ganache-cli
        npm install -g truffle

    - name: Run tests
      run: |
        bash integration-tests.sh

    - uses: codecov/codecov-action@v2
      with:
        flags: integrationtests
