# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Unit Tests

on: [pull-request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.0
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.0

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        pip install -e .

    - name: Test with pytest
      run: |
        bash tests.sh

    - name: Run pre-commit checks
      run: |
        pre-commit run --show-diff-on-failure --from-ref origin/HEAD --to-ref HEAD

    - uses: codecov/codecov-action@v2
      with:
        flags: unittests
